/** @type {import('jest').Config} */
module.exports = {
  preset: "jest-expo",
  resetMocks: true, // clears mock implementations and call history before each test
  restoreMocks: true, // restores mocks created using jest.spyOn and properties swapped with jest.replaceProperty
  collectCoverage: true,
  collectCoverageFrom: ["src/**/*.{ts,tsx}"],
  // src/types/database.types.ts is generated by Supabase
  coveragePathIgnorePatterns: ["src/types/database.types.ts"],
  coverageReporters: ["text"],
  setupFiles: ["./jest.setup.ts"],
};
