#!/usr/bin/env sh
# -e: exit immediately if any command fails
# -u: error on unset variables
set -eu

cd app
pnpm lint-staged
# TODO: only typecheck affected files somehow?
pnpm typecheck

cd ..
pre-commit run
