name: Mobile App
on:
  pull_request:
    paths:
      - .github/workflows/mobile-app.yml
      - .github/actions/setup-app/action.yml
      - app/**

  push:
    paths:
      - .github/workflows/mobile-app.yml
      - .github/actions/setup-app/action.yml
      - app/**
    branches:
      - main

defaults:
  run:
    working-directory: app

env:
  HUSKY: "0"

jobs:
  static-checks-and-unit-test:
    name: Static checks and unit test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint and format
        run: pnpm lint

      - name: Unit test
        run: pnpm test:unit

  e2e_tests_ios:
    name: E2E tests - IOS 📱
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: Generate native iOS project
        run: pnpm expo prebuild --platform ios

      - name: Install simulator
        run: |
          UDID="$(xcrun simctl create "iPhone 12" com.apple.CoreSimulator.SimDeviceType.iPhone-12)"
          echo "UDID=${UDID}" >> "${GITHUB_ENV}"

      - name: Build simulator .app
        run: |
          xcodebuild \
            -workspace "ios/sabr.xcworkspace" \
            -scheme sabr \
            -configuration Release \
            -sdk iphonesimulator \
            -destination "id=${UDID}" \
            -derivedDataPath ios/build \
            build

      - name: Launch simulator
        run: xcrun simctl boot "${UDID}"

      - name: Install app onto simulator
        run: xcrun simctl install booted ios/build/Build/Products/Release-iphonesimulator/sabr.app

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Run Maestro
        env:
          MAESTRO_CLI_NO_ANALYTICS: true
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
        run: pnpm test:e2e

  e2e_tests_android:
    name: E2E tests - Android 🤖
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      # See https://github.com/ReactiveCircus/android-emulator-runner#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Generate native Android project
        run: pnpm expo prebuild --platform android

      # Used to cache Gradle and make builds faster
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build release APK
        run: ./android/gradlew -p android assembleRelease -PreactNativeArchitectures=x86_64

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Run Maestro on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        env:
          MAESTRO_CLI_NO_ANALYTICS: true
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
        with:
          api-level: 34
          arch: x86_64
          working-directory: app
          script: |
            adb install "android/app/build/outputs/apk/release/app-release.apk"
            pnpm test:e2e
