name: Mobile App
on:
  pull_request:
    paths:
      - app/**

  push:
    paths:
      - app/**
    branches:
      - main

env:
  HUSKY: "0"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app

    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: "app/package.json"

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: "app/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "app/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint and Format
        run: pnpm lint

  e2e_tests:
    name: E2E tests (IOS) 📱
    runs-on: macos-latest
    defaults:
      run:
        working-directory: app
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          package_json_file: "app/package.json"

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: "app/.nvmrc"
          cache: "pnpm"
          cache-dependency-path: "app/pnpm-lock.yaml"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate native iOS project
        run: pnpm expo prebuild --platform ios

      - name: Install CocoaPods
        run: pod install --project-directory=ios

      - name: Install and Build Simulator .app
        run: xcodebuild \
          -workspace "ios/sabr.xcworkspace" \
          -scheme sabr \
          -configuration Release \
          -sdk iphonesimulator \
          -destination "id=$(xcrun simctl create 'iPhone 12' com.apple.CoreSimulator.SimDeviceType.iPhone-12)" \
          -derivedDataPath ios/build \
          build

      - name: Install Maestro
        run: curl -fsSL "https://get.maestro.mobile.dev" | bash

      - name: Run Maestro
        run: maestro test .maestro
