name: Mobile App
on:
  pull_request:
    paths:
      - .github/workflows/mobile-app.yml
      - .github/actions/setup-app/action.yml
      - app/**

  push:
    paths:
      - .github/workflows/mobile-app.yml
      - .github/actions/setup-app/action.yml
      - app/**
    branches:
      - main

defaults:
  run:
    working-directory: app

env:
  HUSKY: "0"

jobs:
  static-checks-and-unit-test:
    name: Static checks and unit test 🧪
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: Typecheck
        run: pnpm typecheck

      - name: Lint and format
        run: pnpm lint

      - name: Unit test
        run: pnpm test:unit

  resolve-environment:
    name: Resolve environment
    runs-on: ubuntu-latest
    outputs:
      ENVIRONMENT: ${{ steps.resolve-environment.outputs.ENVIRONMENT }}
      MAESTRO_MAIL_PROVIDER: ${{ steps.resolve-environment.outputs.MAESTRO_MAIL_PROVIDER }}
    steps:
      - id: resolve-environment
        working-directory: .
        run:
          | # When merging to the "develop" branch, or when opening a pull request from "develop" to "main", run e2e tests on staging. Otherwise, run using a local supabase instance.
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref }}" == "refs/heads/develop" ]] \
            || [[ "${{ github.event_name }}" == "pull_request" && "${{ github.base_ref }}" == "main" ]]; then
            echo "ENVIRONMENT=staging" >> "$GITHUB_OUTPUT"
            echo "MAESTRO_MAIL_PROVIDER=resend"  >> "$GITHUB_OUTPUT"
          else
            echo "ENVIRONMENT="         >> "$GITHUB_OUTPUT"
            echo "MAESTRO_MAIL_PROVIDER=mailpit" >> "$GITHUB_OUTPUT"
          fi

      - name: Print outputs
        working-directory: .
        run: echo '${{ toJSON(steps.resolve-environment.outputs) }}'

  e2e_tests_ios:
    name: E2E tests - IOS 📱
    runs-on: macos-26
    # TODO: Docker is not supported on macos-26 runners, and there is no easy way to run it on a macos-26+ runner in a fast and reliable way.
    # The following "if" statement should be removed once Docker is supported on macos-26 runners.
    # See https://github.com/actions/runner-images/issues/13505
    if: ${{ needs.resolve-environment.outputs.MAESTRO_MAIL_PROVIDER != 'mailpit' }}
    needs: resolve-environment
    environment: ${{ needs.resolve-environment.outputs.ENVIRONMENT }}
    env:
      MAESTRO_MAIL_PROVIDER: ${{ needs.resolve-environment.outputs.MAESTRO_MAIL_PROVIDER }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: Set up Supabase CLI
        if: env.MAESTRO_MAIL_PROVIDER == 'mailpit'
        uses: supabase/setup-cli@v2

      - name: Start local Supabase instance
        if: env.MAESTRO_MAIL_PROVIDER == 'mailpit'
        run: |
          supabase start
          eval "$(supabase status -o env)"
          echo "EXPO_PUBLIC_SUPABASE_URL=$API_URL" >> "$GITHUB_ENV"
          echo "EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY" >> "$GITHUB_ENV"
          echo "MAESTRO_MAILPIT_URL=$MAILPIT_URL" >> "$GITHUB_ENV"

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      - name: Generate native iOS project
        run: pnpm expo prebuild --platform ios

      - name: Install simulator
        run: |
          UDID="$(xcrun simctl create "iPhone 12" com.apple.CoreSimulator.SimDeviceType.iPhone-12)"
          echo "UDID=${UDID}" >> "${GITHUB_ENV}"

      - name: Build simulator .app
        run: |
          xcodebuild \
            -workspace "ios/sabr.xcworkspace" \
            -scheme sabr \
            -configuration Release \
            -sdk iphonesimulator \
            -destination "id=${UDID}" \
            -derivedDataPath ios/build \
            build

      - name: Launch simulator
        run: xcrun simctl boot "${UDID}"

      - name: Install app onto simulator
        run: xcrun simctl install booted ios/build/Build/Products/Release-iphonesimulator/sabr.app

      - name: Run Maestro
        env:
          MAESTRO_CLI_NO_ANALYTICS: true
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
        run: pnpm test:e2e

      - name: Upload Maestro debug output
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          path: /home/runner/.maestro/tests/

  e2e_tests_android:
    name: E2E tests - Android 🤖
    runs-on: ubuntu-latest
    needs: resolve-environment
    environment: ${{ needs.resolve-environment.outputs.ENVIRONMENT }}
    env:
      MAESTRO_MAIL_PROVIDER: ${{ needs.resolve-environment.outputs.MAESTRO_MAIL_PROVIDER }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: Set up Supabase CLI
        if: env.MAESTRO_MAIL_PROVIDER == 'mailpit'
        uses: supabase/setup-cli@v2

      - name: Start local Supabase instance
        if: env.MAESTRO_MAIL_PROVIDER == 'mailpit'
        run: |
          supabase start
          eval "$(supabase status -o env)"
          echo "EXPO_PUBLIC_SUPABASE_URL=$API_URL" >> "$GITHUB_ENV"
          echo "EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY" >> "$GITHUB_ENV"
          echo "MAESTRO_MAILPIT_URL=$MAILPIT_URL" >> "$GITHUB_ENV"

      - name: Install Maestro
        run: |
          curl -fsSL "https://get.maestro.mobile.dev" | bash
          echo "$HOME/.maestro/bin" >> "$GITHUB_PATH"

      # See https://github.com/ReactiveCircus/android-emulator-runner#running-hardware-accelerated-emulators-on-linux-runners
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - name: Generate native Android project
        run: pnpm expo prebuild --platform android

      # Used to cache Gradle and make builds faster
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build release APK
        run: ./android/gradlew -p android assembleRelease -PreactNativeArchitectures=x86_64

      - name: Run Maestro on Android emulator
        uses: reactivecircus/android-emulator-runner@v2
        env:
          MAESTRO_CLI_NO_ANALYTICS: true
          MAESTRO_DRIVER_STARTUP_TIMEOUT: 120000
        with:
          api-level: 34
          arch: x86_64
          working-directory: app
          script: |
            adb reverse tcp:54321 tcp:54321
            adb install "android/app/build/outputs/apk/release/app-release.apk"
            pnpm test:e2e

      - name: Upload Maestro debug output
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          path: /home/runner/.maestro/tests/
