name: Continuous Development (PRs)

on:
  pull_request:
    # Assumes all PRs to the main branch will be from the develop branch
    branches-ignore: [main]
    paths:
      - .github/actions/setup-app/action.yml
      - .github/workflows/test-build.yml
      - app/**

env:
  EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

jobs:
  continuously-deploy:
    runs-on: macos-26
    concurrency: continuous-deploy-fingerprint-${{ github.run_id }}
    permissions:
      contents: read # Allow checkout
      pull-requests: write # Allow comments on PRs
    defaults:
      run:
        working-directory: ${{ github.workspace }}/app
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6

      - uses: ./.github/actions/setup-app

      - name: 🏗 Setup EAS CLI
        uses: expo/expo-github-action@main
        env:
          PNPM_CONFIG_STRICT_DEP_BUILDS: "false"
        with:
          packager: pnpm
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Get fingerprint
        id: fingerprint
        uses: expo/expo-github-action/continuous-deploy-fingerprint-info@main
        with:
          profile: development-ios-simulator
          working-directory: ${{ github.workspace }}/app
          # TODO: REMOVE THE LINE BELOW!!!
          platform: ios

      - name: Show action outputs
        run: |
          echo "android-build-id: ${{ steps.fingerprint.outputs.android-build-id }}"
          echo "ios-build-id: ${{ steps.fingerprint.outputs.ios-build-id }}"
          echo "ios-fingerprint: ${{ steps.fingerprint.outputs.ios-fingerprint }}"
          echo "android-fingerprint: ${{ steps.fingerprint.outputs.android-fingerprint }}"

      - name: EAS Build
        if: ${{ steps.fingerprint.outputs.ios-build-id == '' }}
        id: build
        run: |
          BUILD_ID=$(eas build --non-interactive --profile=development-ios-simulator -p ios --json | jq -r '.[0].id')
          echo "BUILD_ID=$BUILD_ID" >> "$GITHUB_OUTPUT"

      - name: Install simulator
        id: install-simulator
        run: |
          SIM_ID="$(xcrun simctl create "iPhone 12" com.apple.CoreSimulator.SimDeviceType.iPhone-12)"
          echo "SIM_ID=${SIM_ID}" >> "$GITHUB_OUTPUT"

      - name: Install EAS Build
        run: eas build:run --id ${{ steps.build.outputs.BUILD_ID || steps.fingerprint.outputs.ios-build-id }} -p ios --simulator steps.install-simulator.outputs.SIM_ID
